# This workflow will run standardrb.
#
# This workflow is pimarily meant to be called by other workflows, but it can be run manually.
name: "🔬 ~ Standardrb"
on:
  workflow_call:
  workflow_dispatch:

jobs:
  # NOTE: This is here just to make the workflow visualization layout better.
  # Without it the layout is really bad and confusing.
  #calculate_matrix:
    #name: 🤷 Fake Matrix
    #runs-on: ubuntu-latest
    #steps:
      #- name: Do Nothing
        #run: echo "This is a useless step that just helps things look nicer..."
        #shell: bash
  lint:
    runs-on: ubuntu-latest
    #needs: calculate_matrix
    env:
      RAILS_ENV: test
      # Manually export your local RAILS_MASTER_KEY if using the credentials system.
      # RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      BUNDLE_JOBS: 2
      BUNDLE_RETRY: 3
    permissions:
      checks: write
      contents: read
    steps:
      - name: Standard Ruby
        uses: standardrb/standard-ruby-action@v1
        with:
          autofix: false
