# This is a dummy workflow that's just here to add a bit of organization to the workflow list
name: "🦥--- Templates Below ---🦥"
on:
  workflow_call:

jobs:
  nothing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
